name: Deploy to EC2

on:
  push:
    branches:
      - main  # adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # use the appropriate operating system
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2-1
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.PRIVATE_KEY_1 }}" | base64 -d | ssh-add -
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-224-229-12.compute-1.amazonaws.com "cd /Team2Hackathon && git pull origin main && npm install && nohup node app.js &"
        shell: bash


